apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - environment-patch.yaml

images:
  - name: registry.legal-suite.com/opencode/app
    newTag: latest

replicas:
  - name: opencode-controller
    count: 2
